"use client";

import { useId, useState } from "react";
import type { ExplanationMeta, Problem } from "@/types/problem";
import { auditExplanation } from "@/lib/explain-audit";
import {
  EXPLAIN_EFFORTS,
  EXPLAIN_MODELS,
  explainModel,
  isSlow,
  suggestedModel,
  type ExplainEffort,
  type ExplainModelId,
} from "@/lib/explain-models";

const EFFORT_LABEL: Record<ExplainEffort, string> = { low: "Low", medium: "Medium", high: "High", xhigh: "Extra high", max: "Max" };

interface Props {
  problem: Problem;
  onGenerated: (problemId: string, explanation: string, meta: ExplanationMeta) => void;
}

/**
 * The explanation under the answer reveal. Nothing is generated on its own: a button asks
 * /api/explain for one with the chosen model (Fable preselected for hard problems) and effort
 * (the model's own default preselected, again when the model changes), and the same button
 * regenerates. Mount with key={problem.id} so the selection resets per problem.
 */
export default function ExplanationPanel({ problem, onGenerated }: Props) {
  const [model, setModel] = useState<ExplainModelId>(() => suggestedModel(problem));
  const [effort, setEffort] = useState<ExplainEffort>(() => explainModel(suggestedModel(problem)).defaultEffort);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Several panels can be on one page (the match review), so the select needs its own id.
  const selectId = useId();
  const effortId = useId();
  const defaultEffort = explainModel(model).defaultEffort;

  const hasText = problem.explanation.length > 0;
  const audit = hasText ? auditExplanation(problem, problem.explanation) : [];

  async function generate() {
    setPending(true);
    setError(null);
    try {
      const res = await fetch("/api/explain", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ problemId: problem.id, model, effort }),
      });
      const data = (await res.json().catch(() => ({}))) as { error?: string; explanation?: string; explanationMeta?: ExplanationMeta };
      if (!res.ok || !data.explanation || !data.explanationMeta) throw new Error(data.error ?? `HTTP ${res.status}`);
      onGenerated(problem.id, data.explanation, data.explanationMeta);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setPending(false);
    }
  }

  return (
    <div className="rounded-lg border border-stone-200 bg-white p-4" data-explanation>
      <h2 className="mb-1 text-sm font-semibold uppercase tracking-wide text-stone-500">Explanation</h2>
      <p className="whitespace-pre-line text-stone-800">
        {hasText ? problem.explanation : <span className="italic text-stone-400">No explanation yet.</span>}
      </p>
      {problem.explanationMeta && (
        <p className="mt-2 text-xs text-stone-400">
          Generated by {problem.explanationMeta.model}
          {problem.explanationMeta.effort && ` at ${problem.explanationMeta.effort} effort`} on {problem.explanationMeta.generatedAt}.
        </p>
      )}
      {audit.length > 0 && (
        <p className="mt-1 text-xs text-amber-700" data-audit>
          Not found in the data: {audit.join(", ")}. Read those with care.
        </p>
      )}
      <div className="mt-3 flex flex-wrap items-center gap-2 text-sm">
        <label htmlFor={selectId} className="text-stone-500">
          Model
        </label>
        <select
          id={selectId}
          data-explain-model
          value={model}
          onChange={(e) => {
            const m = e.target.value as ExplainModelId;
            setModel(m);
            setEffort(explainModel(m).defaultEffort);
          }}
          disabled={pending}
          className="rounded border border-stone-300 bg-white px-2 py-1"
        >
          {EXPLAIN_MODELS.map((m) => (
            <option key={m.id} value={m.id}>
              {m.label} · {m.note}
            </option>
          ))}
        </select>
        <label htmlFor={effortId} className="text-stone-500">
          Effort
        </label>
        <select
          id={effortId}
          data-explain-effort
          value={effort}
          onChange={(e) => setEffort(e.target.value as ExplainEffort)}
          disabled={pending}
          className="rounded border border-stone-300 bg-white px-2 py-1"
          title="How much the model thinks before writing: higher is slower and uses more tokens"
        >
          {EXPLAIN_EFFORTS.map((level) => (
            <option key={level} value={level}>
              {EFFORT_LABEL[level]}
              {level === defaultEffort ? " (default)" : ""}
            </option>
          ))}
        </select>
        <button
          type="button"
          onClick={generate}
          disabled={pending}
          className="rounded bg-stone-800 px-3 py-1.5 font-medium text-white hover:bg-stone-700 disabled:opacity-50"
        >
          {pending ? `Asking ${model}…` : hasText ? "Regenerate" : "Generate explanation"}
        </button>
        {pending && <span className="text-stone-400">{isSlow(model, effort) ? "This can take a minute or more." : "Usually a few seconds."}</span>}
      </div>
      {error && (
        <p className="mt-2 rounded bg-red-50 p-2 text-sm text-red-800" role="alert">
          {error}
        </p>
      )}
    </div>
  );
}
